// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTyb0GBfe_Gwl5PkxzBqq0tEjs41eecJ8',
    appId: '1:177695661505:web:68915e210a0f12e20ce340',
    messagingSenderId: '177695661505',
    projectId: 'fir-flutter-codelab-95738',
    authDomain: 'fir-flutter-codelab-95738.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-95738.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgeTDArXUmMM1PogWlT_n2p-K_qg8OXKU',
    appId: '1:177695661505:android:45544bce03271a5f0ce340',
    messagingSenderId: '177695661505',
    projectId: 'fir-flutter-codelab-95738',
    storageBucket: 'fir-flutter-codelab-95738.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbuui0vV9XoDTyggsF_cYIP1Y3SlZTbs',
    appId: '1:177695661505:ios:2f6a23984771184c0ce340',
    messagingSenderId: '177695661505',
    projectId: 'fir-flutter-codelab-95738',
    storageBucket: 'fir-flutter-codelab-95738.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbuui0vV9XoDTyggsF_cYIP1Y3SlZTbs',
    appId: '1:177695661505:ios:2f6a23984771184c0ce340',
    messagingSenderId: '177695661505',
    projectId: 'fir-flutter-codelab-95738',
    storageBucket: 'fir-flutter-codelab-95738.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTyb0GBfe_Gwl5PkxzBqq0tEjs41eecJ8',
    appId: '1:177695661505:web:e6ea9aea6aa3d7d00ce340',
    messagingSenderId: '177695661505',
    projectId: 'fir-flutter-codelab-95738',
    authDomain: 'fir-flutter-codelab-95738.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-95738.firebasestorage.app',
  );
}
